# Generated by Django 4.2.7 on 2025-10-21 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "case_number",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="شماره پرونده"
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="عنوان پرونده"),
                ),
                ("description", models.TextField(verbose_name="توضیحات")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار"),
                            ("in_progress", "در حال بررسی"),
                            ("completed", "تکمیل\u200cشده"),
                            ("closed", "بسته\u200cشده"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "assigned_lawyer",
                    models.ForeignKey(
                        limit_choices_to={"profile__role": "lawyer"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_cases",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="وکیل مسئول",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_cases",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ایجاد\u200cکننده",
                    ),
                ),
            ],
            options={
                "verbose_name": "پرونده",
                "verbose_name_plural": "پرونده\u200cها",
                "ordering": ["-created_at"],
            },
        ),
    ]
