# Generated by Django 4.2.7 on 2025-10-21 19:06

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("vekalet", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsultationPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("free_consultation", "مشاوره رایگان (15 دقیقه)"),
                            ("hourly_rate", "نرخ ساعتی مشاوره"),
                            ("case_study", "مطالعه و تجزیه\u200cتحلیل پرونده"),
                            ("other", "سایر خدمات"),
                        ],
                        max_length=30,
                        unique=True,
                        verbose_name="نوع خدمت",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="توضیحات خدمت"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        help_text="برای مشاوره رایگان، مقدار 0 وارد کنید",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="قیمت (تومان)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
            ],
            options={
                "verbose_name": "قیمت خدمت",
                "verbose_name_plural": "قیمت\u200cهای خدمات",
                "ordering": ["service_type"],
            },
        ),
        migrations.CreateModel(
            name="Consultation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client_name",
                    models.CharField(max_length=200, verbose_name="نام مراجع"),
                ),
                (
                    "client_phone",
                    models.CharField(max_length=20, verbose_name="شماره تماس"),
                ),
                (
                    "client_national_id",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="کد ملی"
                    ),
                ),
                ("client_address", models.TextField(blank=True, verbose_name="آدرس")),
                (
                    "client_email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="ایمیل"
                    ),
                ),
                (
                    "consultation_subject",
                    models.CharField(max_length=300, verbose_name="موضوع مشاوره"),
                ),
                (
                    "consultation_details",
                    models.TextField(blank=True, verbose_name="جزئیات مشاوره"),
                ),
                (
                    "consultation_date",
                    models.DateTimeField(verbose_name="تاریخ و ساعت مشاوره"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار مشاوره"),
                            ("completed", "مشاوره انجام\u200cشده"),
                            ("converted_to_case", "تبدیل\u200cشده به پرونده"),
                            ("cancelled", "لغو\u200cشده"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "consultation_fee",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        help_text="اگر مشاوره رایگان است، 0 وارد کنید",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="هزینه مشاوره (تومان)",
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("free", "رایگان"),
                            ("unpaid", "پرداخت\u200cنشده"),
                            ("paid", "پرداخت\u200cشده"),
                            ("partial", "جزئی\u200c پرداخت\u200cشده"),
                        ],
                        default="free",
                        max_length=20,
                        verbose_name="وضعیت پرداخت",
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="مبلغ پرداخت\u200cشده (تومان)",
                    ),
                ),
                (
                    "conversion_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاریخ تبدیل به پرونده"
                    ),
                ),
                (
                    "final_contract_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="مبلغ نهایی قرارداد (تومان)",
                    ),
                ),
                (
                    "conversion_notes",
                    models.TextField(blank=True, verbose_name="توضیحات تبدیل"),
                ),
                (
                    "notes",
                    models.TextField(blank=True, verbose_name="یادداشت\u200cهای کلی"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ثبت"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "assigned_lawyer",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"profile__role": "lawyer"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consultations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="وکیل مسئول",
                    ),
                ),
                (
                    "converted_to_case",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consultation_source",
                        to="vekalet.casefile",
                        verbose_name="تبدیل\u200cشده به پرونده",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_consultations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ثبت\u200cکننده",
                    ),
                ),
            ],
            options={
                "verbose_name": "مشاوره",
                "verbose_name_plural": "مشاورات",
                "ordering": ["-consultation_date"],
            },
        ),
    ]
