# Generated by Django 4.2.7 on 2025-10-21 19:17

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("vekalet", "0002_consultationprice_consultation"),
    ]

    operations = [
        migrations.AddField(
            model_name="casefile",
            name="case_details",
            field=models.TextField(blank=True, verbose_name="جزئیات تفصیلی"),
        ),
        migrations.AddField(
            model_name="casefile",
            name="case_end_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="تاریخ پایان پرونده"
            ),
        ),
        migrations.AddField(
            model_name="casefile",
            name="case_start_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="تاریخ شروع پرونده"
            ),
        ),
        migrations.AddField(
            model_name="casefile",
            name="case_type",
            field=models.CharField(
                choices=[("legal", "حقوقی"), ("judicial", "قضایی"), ("other", "سایر")],
                default="legal",
                max_length=20,
                verbose_name="نوع پرونده",
            ),
        ),
        migrations.AddField(
            model_name="casefile",
            name="client_address",
            field=models.TextField(blank=True, verbose_name="آدرس مراجع"),
        ),
        migrations.AddField(
            model_name="casefile",
            name="client_name",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="نام مراجع/موکل"
            ),
        ),
        migrations.AddField(
            model_name="casefile",
            name="client_national_id",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="کد ملی مراجع"
            ),
        ),
        migrations.AddField(
            model_name="casefile",
            name="client_phone",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="تلفن مراجع"
            ),
        ),
        migrations.AddField(
            model_name="casefile",
            name="co_lawyers",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"profile__role": "lawyer"},
                related_name="co_assigned_cases",
                to=settings.AUTH_USER_MODEL,
                verbose_name="وکلای همکار",
            ),
        ),
        migrations.AddField(
            model_name="casefile",
            name="contract_amount",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="مبلغ قرارداد (تومان)",
            ),
        ),
        migrations.AddField(
            model_name="casefile",
            name="court_case_number",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="شماره پرونده دادگاه"
            ),
        ),
        migrations.AddField(
            model_name="casefile",
            name="court_name",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="نام دادگاه"
            ),
        ),
        migrations.AddField(
            model_name="casefile",
            name="judge_name",
            field=models.CharField(blank=True, max_length=200, verbose_name="نام قاضی"),
        ),
        migrations.AddField(
            model_name="casefile",
            name="legal_basis",
            field=models.TextField(
                blank=True, verbose_name="مبنای قانونی/ماده\u200cهای مربوط"
            ),
        ),
        migrations.AddField(
            model_name="casefile",
            name="next_hearing_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="تاریخ جلسه بعدی"
            ),
        ),
        migrations.AddField(
            model_name="casefile",
            name="notes",
            field=models.TextField(blank=True, verbose_name="یادداشت\u200cهای کلی"),
        ),
        migrations.AddField(
            model_name="casefile",
            name="paid_amount",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="مبلغ پرداخت\u200cشده (تومان)",
            ),
        ),
        migrations.AddField(
            model_name="casefile",
            name="priority",
            field=models.CharField(
                choices=[
                    ("low", "کم"),
                    ("medium", "متوسط"),
                    ("high", "بالا"),
                    ("urgent", "فوری"),
                ],
                default="medium",
                max_length=20,
                verbose_name="اولویت",
            ),
        ),
        migrations.AlterField(
            model_name="casefile",
            name="description",
            field=models.TextField(blank=True, verbose_name="توضیحات و خلاصه پرونده"),
        ),
        migrations.CreateModel(
            name="CaseFileAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attachment_type",
                    models.CharField(
                        choices=[
                            ("document", "سند"),
                            ("contract", "قرارداد"),
                            ("evidence", "مدرک/شاهد"),
                            ("court_order", "دستور دادگاه"),
                            ("letter", "نامه"),
                            ("photo", "عکس"),
                            ("other", "سایر"),
                        ],
                        default="document",
                        max_length=20,
                        verbose_name="نوع پیوست",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان پیوست")),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                (
                    "file",
                    models.FileField(
                        upload_to="case_attachments/%Y/%m/%d/", verbose_name="فایل"
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاریخ بارگذاری"
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="vekalet.casefile",
                        verbose_name="پرونده",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="بارگذاری\u200cشده توسط",
                    ),
                ),
            ],
            options={
                "verbose_name": "پیوست پرونده",
                "verbose_name_plural": "پیوست\u200cهای پرونده",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
