# Generated by Django 4.2.7 on 2025-10-22 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("vekalet", "0003_casefile_case_details_casefile_case_end_date_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="casefileattachment",
            options={
                "ordering": ["-uploaded_at"],
                "verbose_name": "پیوست پرونده یا مشاوره",
                "verbose_name_plural": "پیوست\u200cهای پرونده و مشاورات",
            },
        ),
        migrations.AddField(
            model_name="casefileattachment",
            name="consultation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="vekalet.consultation",
                verbose_name="مشاوره",
            ),
        ),
        migrations.AlterField(
            model_name="casefileattachment",
            name="case",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="vekalet.casefile",
                verbose_name="پرونده",
            ),
        ),
    ]
