# Generated by Django 4.2.7 on 2025-10-18 17:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_home",
                    models.CharField(
                        blank=True,
                        max_length=11,
                        null=True,
                        verbose_name="شماره تلفن ثابت",
                    ),
                ),
                (
                    "phone_mobile",
                    models.CharField(max_length=11, verbose_name="شماره تلفن موبایل"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="آدرس ایمیل"
                    ),
                ),
                ("address", models.TextField(verbose_name="آدرس کامل")),
                (
                    "postal_code",
                    models.CharField(max_length=10, verbose_name="کد پستی"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "اطلاعات تماس",
                "verbose_name_plural": "اطلاعات تماس",
            },
        ),
        migrations.CreateModel(
            name="IdentityDocuments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="نام")),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="نام خانوادگی"),
                ),
                (
                    "national_id",
                    models.CharField(max_length=10, unique=True, verbose_name="کد ملی"),
                ),
                (
                    "certificate_number",
                    models.CharField(max_length=20, verbose_name="شماره شناسنامه"),
                ),
                (
                    "birth_date",
                    django_jalali.db.models.jDateField(verbose_name="تاریخ تولد"),
                ),
                (
                    "birth_place",
                    models.CharField(max_length=100, verbose_name="محل صدور شناسنامه"),
                ),
                (
                    "national_id_image",
                    models.ImageField(
                        help_text="فرمت\u200cهای مجاز: JPG, PNG (حداکثر 10 مگابایت)",
                        upload_to="documents/national_id/%Y/%m/%d/",
                        verbose_name="عکس کارت ملی",
                    ),
                ),
                (
                    "additional_documents",
                    models.FileField(
                        blank=True,
                        help_text="PDF, ZIP یا سایر فرمت\u200cها (حداکثر 10 مگابایت)",
                        null=True,
                        upload_to="documents/additional/%Y/%m/%d/",
                        verbose_name="سایر مدارک",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
            ],
            options={
                "verbose_name": "مدارک هویتی",
                "verbose_name_plural": "مدارک هویتی",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RegistryServiceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("licenses", "مجوزها"),
                            ("trade", "بازرگانی"),
                            ("companies", "شرکت\u200cها"),
                        ],
                        max_length=50,
                        unique=True,
                        verbose_name="نام دسته",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="توضیحات کلی"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "دسته خدمات ثبتی",
                "verbose_name_plural": "دسته\u200cهای خدمات ثبتی",
            },
        ),
        migrations.CreateModel(
            name="TradePartnership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("natural", "حقیقی"),
                            ("legal", "حقوقی"),
                            ("productive", "تولیدی"),
                        ],
                        max_length=50,
                        verbose_name="نوع مشارکت",
                    ),
                ),
                ("card_year", models.IntegerField(verbose_name="سال اخذ کارت")),
                (
                    "import_ceiling",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="سقف واردات",
                    ),
                ),
                (
                    "export_ceiling",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="سقف صادرات",
                    ),
                ),
                (
                    "import_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="مبلغ واردات",
                    ),
                ),
                (
                    "export_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="مبلغ صادرات",
                    ),
                ),
                (
                    "amount_received",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="مبلغ دریافتی",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="توضیحات"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contact_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trade_partnerships",
                        to="registry.contactinfo",
                        verbose_name="اطلاعات تماس",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_trade_partnerships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "identity_documents",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trade_partnerships",
                        to="registry.identitydocuments",
                        verbose_name="مدارک هویتی",
                    ),
                ),
            ],
            options={
                "verbose_name": "مشارکت بازرگانی",
                "verbose_name_plural": "مشارکت\u200cهای بازرگانی",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TradeAcquisition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[("legal", "حقوقی"), ("natural", "حقیقی")],
                        max_length=50,
                        verbose_name="نوع اخذ",
                    ),
                ),
                (
                    "acquisition_type",
                    models.CharField(max_length=200, verbose_name="نوع اخذ تفصیلی"),
                ),
                (
                    "check_category",
                    models.CharField(
                        choices=[
                            ("check_a", "دسته الف"),
                            ("check_b", "دسته ب"),
                            ("check_c", "دسته ج"),
                        ],
                        max_length=50,
                        verbose_name="دسته چک",
                    ),
                ),
                (
                    "amount_received",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="مبلغ دریافتی",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="توضیحات"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contact_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trade_acquisitions",
                        to="registry.contactinfo",
                        verbose_name="اطلاعات تماس",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_trade_acquisitions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "identity_documents",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trade_acquisitions",
                        to="registry.identitydocuments",
                        verbose_name="مدارک هویتی",
                    ),
                ),
            ],
            options={
                "verbose_name": "اخذ بازرگانی",
                "verbose_name_plural": "اخذ\u200cهای بازرگانی",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="License",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subcategory",
                    models.CharField(
                        choices=[
                            ("household", "خانگی"),
                            ("professional", "صنفی"),
                            ("other", "سایر"),
                        ],
                        max_length=50,
                        verbose_name="دسته\u200cبندی جزئی",
                    ),
                ),
                (
                    "service_title",
                    models.CharField(max_length=200, verbose_name="عنوان خدمت"),
                ),
                (
                    "amount_received",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="مبلغ دریافتی",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="توضیحات"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contact_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="licenses",
                        to="registry.contactinfo",
                        verbose_name="اطلاعات تماس",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_licenses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "identity_documents",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="licenses",
                        to="registry.identitydocuments",
                        verbose_name="مدارک هویتی",
                    ),
                ),
            ],
            options={
                "verbose_name": "مجوز",
                "verbose_name_plural": "مجوزها",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_type",
                    models.CharField(
                        choices=[
                            ("limited_liability", "مسئولیت محدود"),
                            ("joint_stock", "سهامی عام"),
                            ("cooperative", "تعاونی"),
                            ("transport", "حمل و نقل"),
                        ],
                        max_length=50,
                        verbose_name="نوع شرکت",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(max_length=200, verbose_name="نام شرکت"),
                ),
                (
                    "has_license",
                    models.BooleanField(
                        default=False, verbose_name="آیا مجوز موجود است؟"
                    ),
                ),
                (
                    "license_file",
                    models.FileField(
                        blank=True,
                        help_text="الزامی اگر مجوز موجود باشد (حداکثر 10 مگابایت)",
                        null=True,
                        upload_to="documents/licenses/%Y/%m/%d/",
                        verbose_name="فایل مجوز",
                    ),
                ),
                (
                    "amount_received",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="مبلغ دریافتی",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="توضیحات"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contact_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="companies",
                        to="registry.contactinfo",
                        verbose_name="اطلاعات تماس",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_companies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "identity_documents",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="companies",
                        to="registry.identitydocuments",
                        verbose_name="مدارک هویتی",
                    ),
                ),
            ],
            options={
                "verbose_name": "شرکت",
                "verbose_name_plural": "شرکت\u200cها",
                "ordering": ["-created_at"],
            },
        ),
    ]
