# Generated by Django 4.2.7 on 2025-10-18 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0001_initial"),
    ]

    operations = [
        # اضافه کردن فیلدهای شناخت‌شخص با default values
        migrations.AddField(
            model_name='contactinfo',
            name='نام',
            field=models.CharField(default='نامشخص', max_length=100, verbose_name='نام'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='نام_خانوادگی',
            field=models.CharField(default='نامشخص', max_length=100, verbose_name='نام خانوادگی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='کد_ملی',
            field=models.CharField(default='0000000000', max_length=10, unique=True, verbose_name='کد ملی'),
            preserve_default=False,
        ),
        # تغییر نام فیلدهای موجود
        migrations.RenameField(
            model_name='contactinfo',
            old_name='phone_home',
            new_name='تلفن_ثابت',
        ),
        migrations.RenameField(
            model_name='contactinfo',
            old_name='phone_mobile',
            new_name='تلفن_موبایل',
        ),
        migrations.RenameField(
            model_name='contactinfo',
            old_name='email',
            new_name='ایمیل',
        ),
        migrations.RenameField(
            model_name='contactinfo',
            old_name='address',
            new_name='آدرس',
        ),
        migrations.RenameField(
            model_name='contactinfo',
            old_name='postal_code',
            new_name='کد_پستی',
        ),
        # اضافه کردن verbose_name به فیلدهای موجود
        migrations.AlterField(
            model_name='contactinfo',
            name='تلفن_ثابت',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره تلفن ثابت'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='تلفن_موبایل',
            field=models.CharField(max_length=11, verbose_name='شماره تلفن موبایل'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='ایمیل',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='آدرس ایمیل'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='آدرس',
            field=models.TextField(verbose_name='آدرس کامل'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='کد_پستی',
            field=models.CharField(max_length=10, verbose_name='کد پستی'),
        ),
        # اضافه کردن verbose_name به متاداده
        migrations.AlterField(
            model_name='contactinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
        # تغییر Meta class ordering
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'ordering': ['-created_at'], 'verbose_name': 'اطلاعات تماس', 'verbose_name_plural': 'اطلاعات تماس'},
        ),
    ]