# Generated by Django 4.2.7 on 2025-10-18 18:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0002_update_contactinfo_fields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tradeacquisition",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "دریافت بازرگانی",
                "verbose_name_plural": "دریافت\u200cهای بازرگانی",
            },
        ),
        migrations.AlterModelOptions(
            name="tradepartnership",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "کارت بازرگانی",
                "verbose_name_plural": "کارت\u200cهای بازرگانی",
            },
        ),
        migrations.AlterField(
            model_name="tradeacquisition",
            name="acquisition_type",
            field=models.CharField(max_length=200, verbose_name="نوع دریافت تفصیلی"),
        ),
        migrations.AlterField(
            model_name="tradeacquisition",
            name="entity_type",
            field=models.CharField(
                choices=[("legal", "حقوقی"), ("natural", "حقیقی")],
                max_length=50,
                verbose_name="نوع دریافت",
            ),
        ),
        migrations.AlterField(
            model_name="tradepartnership",
            name="card_year",
            field=models.IntegerField(verbose_name="سال دریافت کارت"),
        ),
        migrations.AlterField(
            model_name="tradepartnership",
            name="entity_type",
            field=models.CharField(
                choices=[
                    ("natural", "حقیقی"),
                    ("legal", "حقوقی"),
                    ("productive", "تولیدی"),
                ],
                max_length=50,
                verbose_name="نوع کارت بازرگانی",
            ),
        ),
    ]
