# Generated by Django 4.2.7 on 2025-10-18 18:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0003_alter_tradeacquisition_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contactinfo",
            old_name="ایمیل",
            new_name="email",
        ),
        migrations.RenameField(
            model_name="contactinfo",
            old_name="نام",
            new_name="first_name",
        ),
        migrations.RenameField(
            model_name="contactinfo",
            old_name="نام_خانوادگی",
            new_name="last_name",
        ),
        migrations.RenameField(
            model_name="contactinfo",
            old_name="کد_ملی",
            new_name="national_id",
        ),
        migrations.RenameField(
            model_name="contactinfo",
            old_name="تلفن_ثابت",
            new_name="phone_number",
        ),
        migrations.RemoveField(
            model_name="contactinfo",
            name="آدرس",
        ),
        migrations.RemoveField(
            model_name="contactinfo",
            name="تلفن_موبایل",
        ),
        migrations.RemoveField(
            model_name="contactinfo",
            name="کد_پستی",
        ),
        migrations.AddField(
            model_name="contactinfo",
            name="address",
            field=models.TextField(blank=True, null=True, verbose_name="آدرس کامل"),
        ),
        migrations.AddField(
            model_name="contactinfo",
            name="mobile_number",
            field=models.CharField(
                blank=True, max_length=11, null=True, verbose_name="شماره تلفن موبایل"
            ),
        ),
        migrations.AddField(
            model_name="contactinfo",
            name="postal_code",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="کد پستی"
            ),
        ),
    ]
