# Generated by Django 4.2.7 on 2025-10-18 19:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0004_rename_ایمیل_contactinfo_email_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tradeacquisition",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "بازرگانی اخذ",
                "verbose_name_plural": "بازرگانی\u200cهای اخذ",
            },
        ),
        migrations.AlterModelOptions(
            name="tradepartnership",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "بازرگانی مشارکتی",
                "verbose_name_plural": "بازرگانی\u200cهای مشارکتی",
            },
        ),
        migrations.AlterField(
            model_name="tradeacquisition",
            name="check_category",
            field=models.CharField(
                choices=[("has", "دارد"), ("no", "ندارد")],
                max_length=50,
                verbose_name="دسته چک",
            ),
        ),
    ]
