# Generated by Django 4.2.7 on 2025-10-21 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("registry", "0005_alter_tradeacquisition_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactinfo",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_contact_infos",
                to=settings.AUTH_USER_MODEL,
                verbose_name="ثبت\u200cکننده",
            ),
        ),
        migrations.AddField(
            model_name="identitydocuments",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_identity_documents",
                to=settings.AUTH_USER_MODEL,
                verbose_name="ثبت\u200cکننده",
            ),
        ),
    ]
