# Generated by Django 4.2.7 on 2025-10-16 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0002_branch_financialreport_loan_service_revenue_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="branch",
            options={
                "ordering": ["name"],
                "verbose_name": "شعبه",
                "verbose_name_plural": "شعبه\u200cها",
            },
        ),
        migrations.AlterModelOptions(
            name="employee",
            options={
                "ordering": ["user__first_name", "user__last_name"],
                "verbose_name": "کارمند",
                "verbose_name_plural": "کارمندان",
            },
        ),
        migrations.RemoveField(
            model_name="employee",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="salary",
        ),
        migrations.AddField(
            model_name="branch",
            name="branch_type",
            field=models.CharField(
                choices=[
                    ("headquarters", "مرکزی"),
                    ("agency", "نمایندگی"),
                    ("store", "فروشگاه"),
                    ("office", "دفتر"),
                    ("other", "دیگر"),
                ],
                default="office",
                max_length=50,
                verbose_name="نوع شعبه",
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="city",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="شهر"
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="code",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="کد شعبه",
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="توضیحات داخلی"),
        ),
        migrations.AddField(
            model_name="branch",
            name="founding_date",
            field=django_jalali.db.models.jDateField(
                blank=True, null=True, verbose_name="تاریخ تأسیس"
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="monthly_budget",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=15,
                null=True,
                verbose_name="بودجه ماهانه",
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="postal_code",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="کد پستی"
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="province",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="استان"
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "فعال"),
                    ("inactive", "غیرفعال"),
                    ("temporary_close", "تعطیل موقت"),
                ],
                default="active",
                max_length=20,
                verbose_name="وضعیت فعالیت",
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="working_hours",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="ساعت کاری (مثال: ۸-۱۶)",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="address",
            field=models.TextField(
                blank=True, null=True, verbose_name="آدرس محل سکونت"
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="bank_account_number",
            field=models.CharField(
                blank=True, max_length=24, null=True, verbose_name="شماره حساب بانکی"
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="base_salary",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="حقوق پایه",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="benefits",
            field=models.TextField(
                blank=True, null=True, verbose_name="مزایا و اضافه کاری"
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="birth_date",
            field=django_jalali.db.models.jDateField(
                blank=True, null=True, verbose_name="تاریخ تولد"
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="contract_end_date",
            field=django_jalali.db.models.jDateField(
                blank=True, null=True, verbose_name="تاریخ پایان قرارداد"
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="contract_type",
            field=models.CharField(
                choices=[
                    ("full_time", "تمام وقت"),
                    ("part_time", "پاره وقت"),
                    ("project_based", "پروژه\u200cای"),
                    ("temporary", "موقت"),
                    ("intern", "کارآموزی"),
                ],
                default="full_time",
                max_length=50,
                verbose_name="نوع قرارداد",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="education",
            field=models.TextField(blank=True, null=True, verbose_name="تحصیلات"),
        ),
        migrations.AddField(
            model_name="employee",
            name="employment_status",
            field=models.CharField(
                choices=[
                    ("active", "فعال"),
                    ("leave", "مرخصی"),
                    ("inactive", "غیرفعال"),
                    ("terminated", "اخراج"),
                ],
                default="active",
                max_length=20,
                verbose_name="وضعیت فعلی",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "مرد"), ("F", "زن")],
                max_length=1,
                null=True,
                verbose_name="جنسیت",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="insurance_info",
            field=models.TextField(
                blank=True, null=True, verbose_name="بیمه و مزایای رفاهی"
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="internal_notes",
            field=models.TextField(
                blank=True, null=True, verbose_name="یادداشت\u200cهای داخلی"
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="national_id",
            field=models.CharField(
                blank=True, max_length=10, null=True, unique=True, verbose_name="کد ملی"
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="payment_method",
            field=models.CharField(
                choices=[("bank", "بانکی"), ("cash", "نقدی"), ("both", "هردو")],
                default="bank",
                max_length=20,
                verbose_name="روش پرداخت",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="personnel_id",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="شماره پرسنلی",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="phone",
            field=models.CharField(
                blank=True, max_length=11, null=True, verbose_name="شماره تماس"
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="employee_pictures/",
                verbose_name="عکس پرسنلی",
            ),
        ),
        migrations.AlterField(
            model_name="branch",
            name="address",
            field=models.TextField(verbose_name="آدرس کامل"),
        ),
        migrations.AlterField(
            model_name="branch",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_branches",
                to=settings.AUTH_USER_MODEL,
                verbose_name="مدیر شعبه",
            ),
        ),
        migrations.AlterField(
            model_name="branch",
            name="name",
            field=models.CharField(max_length=150, verbose_name="نام شعبه"),
        ),
        migrations.AlterField(
            model_name="branch",
            name="phone",
            field=models.CharField(max_length=11, verbose_name="شماره تلفن"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employees",
                to="core.branch",
                verbose_name="دپارتمان/شعبه",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="hire_date",
            field=django_jalali.db.models.jDateField(verbose_name="تاریخ استخدام"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="job_title",
            field=models.CharField(
                choices=[
                    ("manager", "مدیر"),
                    ("officer", "افسر"),
                    ("assistant", "دستیار"),
                    ("intern", "کارآموز"),
                    ("lawyer", "وکیل"),
                    ("accountant", "حسابدار"),
                    ("hr", "منابع انسانی"),
                    ("it", "فناوری اطلاعات"),
                    ("other", "دیگر"),
                ],
                max_length=50,
                verbose_name="سمت/شغل",
            ),
        ),
    ]
