# Generated by Django 4.2.7 on 2025-10-16 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0003_alter_branch_options_alter_employee_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="expense",
            options={
                "ordering": ["-registration_date"],
                "verbose_name": "هزینه",
                "verbose_name_plural": "هزینه\u200cها",
            },
        ),
        migrations.AlterModelOptions(
            name="loan",
            options={
                "ordering": ["-registration_date"],
                "verbose_name": "وام",
                "verbose_name_plural": "وام\u200cها",
            },
        ),
        migrations.AlterModelOptions(
            name="loanbuyer",
            options={
                "ordering": ["-application_date"],
                "verbose_name": "خریدار وام",
                "verbose_name_plural": "خریداران وام",
            },
        ),
        migrations.AlterModelOptions(
            name="revenue",
            options={
                "verbose_name": "درآمد (قدیمی)",
                "verbose_name_plural": "درآمدها (قدیمی)",
            },
        ),
        migrations.RemoveField(
            model_name="expense",
            name="date",
        ),
        migrations.RemoveField(
            model_name="expense",
            name="expense_type",
        ),
        migrations.RemoveField(
            model_name="expense",
            name="report",
        ),
        migrations.RemoveField(
            model_name="loan",
            name="interest_rate",
        ),
        migrations.RemoveField(
            model_name="loan",
            name="loan_number",
        ),
        migrations.RemoveField(
            model_name="loanbuyer",
            name="address",
        ),
        migrations.RemoveField(
            model_name="loanbuyer",
            name="monthly_payment",
        ),
        migrations.RemoveField(
            model_name="loanbuyer",
            name="purchase_date",
        ),
        migrations.RemoveField(
            model_name="loanbuyer",
            name="remaining_balance",
        ),
        migrations.RemoveField(
            model_name="loanbuyer",
            name="user",
        ),
        migrations.AddField(
            model_name="expense",
            name="attachment",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="expense_documents/",
                verbose_name="سند مالی/فاکتور/رسید",
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="expenses",
                to="core.branch",
                verbose_name="شعبه",
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="category",
            field=models.CharField(
                choices=[
                    ("salary", "حقوق و دستمزد"),
                    ("rent", "اجاره"),
                    ("utilities", "خدمات و قبوض"),
                    ("equipment", "خرید مواد و تجهیزات"),
                    ("services", "خدمات"),
                    ("tax", "مالیات"),
                    ("travel", "سفر"),
                    ("other", "دیگر"),
                ],
                default="other",
                max_length=50,
                verbose_name="دسته\u200cبندی هزینه",
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="financial_report",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="expenses",
                to="core.financialreport",
                verbose_name="گزارش مالی",
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="is_verified",
            field=models.BooleanField(default=False, verbose_name="بررسی شده"),
        ),
        migrations.AddField(
            model_name="expense",
            name="payment_date",
            field=django_jalali.db.models.jDateField(
                blank=True, null=True, verbose_name="تاریخ واقعی پرداخت"
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "نقدی"),
                    ("card", "کارت"),
                    ("transfer", "انتقال بانکی"),
                    ("check", "چک"),
                    ("other", "دیگر"),
                ],
                default="cash",
                max_length=50,
                verbose_name="روش پرداخت",
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("paid", "پرداخت شده"),
                    ("pending", "در انتظار"),
                    ("returned", "برگشت خورده"),
                ],
                default="pending",
                max_length=20,
                verbose_name="وضعیت پرداخت",
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="recorded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recorded_expenses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="مسئول ثبت/پرداخت",
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="registration_date",
            field=django_jalali.db.models.jDateField(
                blank=True, null=True, verbose_name="تاریخ ثبت"
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="loan",
            name="bank_name",
            field=models.CharField(default="", max_length=150, verbose_name="نام بانک"),
        ),
        migrations.AddField(
            model_name="loan",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="loans",
                to="core.branch",
                verbose_name="شعبه مربوطه",
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="loan_type",
            field=models.CharField(
                choices=[
                    ("residential", "مسکن"),
                    ("personal", "شخصی"),
                    ("auto", "خودرو"),
                    ("business", "کسب\u200cوکار"),
                    ("other", "دیگر"),
                ],
                default="other",
                max_length=50,
                verbose_name="نوع وام",
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="payment_type",
            field=models.CharField(
                choices=[("cash", "نقدی"), ("installment", "اقساطی")],
                default="installment",
                max_length=50,
                verbose_name="نوع پرداخت",
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="purchase_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="نرخ خرید (درصد کارمزد/سود)",
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="registration_date",
            field=django_jalali.db.models.jDateField(
                blank=True, null=True, verbose_name="تاریخ مراجعه/ثبت وام"
            ),
        ),
        migrations.AddField(
            model_name="loanbuyer",
            name="application_date",
            field=django_jalali.db.models.jDateField(
                blank=True, null=True, verbose_name="تاریخ مراجعه/ثبت درخواست"
            ),
        ),
        migrations.AddField(
            model_name="loanbuyer",
            name="bank",
            field=models.CharField(
                default="", max_length=150, verbose_name="بانک عامل"
            ),
        ),
        migrations.AddField(
            model_name="loanbuyer",
            name="broker",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"profile__role": "employee"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="loan_buyers_as_broker",
                to=settings.AUTH_USER_MODEL,
                verbose_name="کارگذار ثبت\u200cکننده",
            ),
        ),
        migrations.AddField(
            model_name="loanbuyer",
            name="current_status",
            field=models.CharField(
                choices=[
                    ("registered", "ثبت درخواست"),
                    ("under_review", "در حال بررسی"),
                    ("qualification_transfer", "انتقال امتیاز"),
                    ("bank_validation", "اعتبار سنجی بانک"),
                    ("loan_paid", "پرداخت وام"),
                    ("guarantor_defective", "نقص ضامن"),
                    ("borrower_defective", "نقص وام گیرنده"),
                ],
                default="registered",
                max_length=50,
                verbose_name="وضعیت فعلی",
            ),
        ),
        migrations.AddField(
            model_name="loanbuyer",
            name="first_name",
            field=models.CharField(default="", max_length=100, verbose_name="نام"),
        ),
        migrations.AddField(
            model_name="loanbuyer",
            name="internal_notes",
            field=models.TextField(
                blank=True, null=True, verbose_name="یادداشت\u200cهای داخلی"
            ),
        ),
        migrations.AddField(
            model_name="loanbuyer",
            name="last_name",
            field=models.CharField(
                default="", max_length=100, verbose_name="نام خانوادگی"
            ),
        ),
        migrations.AddField(
            model_name="loanbuyer",
            name="requested_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=15, verbose_name="مبلغ درخواستی"
            ),
        ),
        migrations.AddField(
            model_name="loanbuyer",
            name="sale_price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=15, verbose_name="قیمت فروش"
            ),
        ),
        migrations.AddField(
            model_name="loanbuyer",
            name="sale_type",
            field=models.CharField(
                choices=[("cash", "نقدی"), ("conditional", "شرایطی")],
                default="cash",
                max_length=20,
                verbose_name="نوع فروش",
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=15, verbose_name="مبلغ هزینه"
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="توضیحات داخلی"),
        ),
        migrations.AlterField(
            model_name="expense",
            name="title",
            field=models.CharField(max_length=200, verbose_name="عنوان/توضیح هزینه"),
        ),
        migrations.AlterField(
            model_name="loan",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=15, verbose_name="مبلغ وام"
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="توضیحات داخلی"),
        ),
        migrations.AlterField(
            model_name="loan",
            name="duration_months",
            field=models.IntegerField(default=0, verbose_name="مدت وام (به ماه)"),
        ),
        migrations.AlterField(
            model_name="loan",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "موجود"),
                    ("unsuccessful", "ناموفق"),
                    ("purchased", "خریدشده"),
                ],
                default="available",
                max_length=20,
                verbose_name="وضعیت وام",
            ),
        ),
        migrations.AlterField(
            model_name="loanbuyer",
            name="loan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="buyers",
                to="core.loan",
                verbose_name="وام هدف",
            ),
        ),
        migrations.AlterField(
            model_name="loanbuyer",
            name="national_id",
            field=models.CharField(
                default="", max_length=10, unique=True, verbose_name="کد ملی"
            ),
        ),
        migrations.AlterField(
            model_name="loanbuyer",
            name="phone",
            field=models.CharField(
                default="", max_length=11, verbose_name="شماره تماس"
            ),
        ),
        migrations.AlterField(
            model_name="loancreditor",
            name="address",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="loancreditor",
            name="credit_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="loancreditor",
            name="organization_name",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="loancreditor",
            name="phone",
            field=models.CharField(default="", max_length=11),
        ),
        migrations.AlterField(
            model_name="loancreditor",
            name="remaining_debt",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.CreateModel(
            name="LoanBuyerStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("registered", "ثبت درخواست"),
                            ("under_review", "در حال بررسی"),
                            ("qualification_transfer", "انتقال امتیاز"),
                            ("bank_validation", "اعتبار سنجی بانک"),
                            ("loan_paid", "پرداخت وام"),
                            ("guarantor_defective", "نقص ضامن"),
                            ("borrower_defective", "نقص وام گیرنده"),
                        ],
                        default="registered",
                        max_length=50,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "status_date",
                    django_jalali.db.models.jDateField(
                        blank=True, null=True, verbose_name="تاریخ ثبت وضعیت"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="توضیحات اختیاری"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "loan_buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="core.loanbuyer",
                        verbose_name="خریدار وام",
                    ),
                ),
            ],
            options={
                "verbose_name": "تاریخچه وضعیت خریدار وام",
                "verbose_name_plural": "تاریخچه\u200cهای وضعیت خریدار وام",
                "ordering": ["loan_buyer", "-status_date"],
            },
        ),
        migrations.CreateModel(
            name="Income",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="عنوان/توضیح درآمد"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="توضیحات داخلی"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="مبلغ درآمد"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "نقدی"),
                            ("card", "کارت"),
                            ("transfer", "انتقال بانکی"),
                            ("check", "چک"),
                            ("other", "دیگر"),
                        ],
                        default="cash",
                        max_length=50,
                        verbose_name="روش دریافت",
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("received", "دریافت شده"),
                            ("pending", "در انتظار"),
                            ("returned", "برگشت خورده"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="وضعیت پرداخت",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("sales", "فروش"),
                            ("services", "خدمات"),
                            ("rent", "اجاره"),
                            ("interest", "سود"),
                            ("other", "دیگر"),
                        ],
                        default="other",
                        max_length=50,
                        verbose_name="دسته\u200cبندی درآمد",
                    ),
                ),
                (
                    "registration_date",
                    django_jalali.db.models.jDateField(
                        blank=True, null=True, verbose_name="تاریخ ثبت"
                    ),
                ),
                (
                    "received_date",
                    django_jalali.db.models.jDateField(
                        blank=True, null=True, verbose_name="تاریخ واقعی دریافت"
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="بررسی شده"),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="income_documents/",
                        verbose_name="سند مالی/فاکتور",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incomes",
                        to="core.branch",
                        verbose_name="شعبه",
                    ),
                ),
                (
                    "financial_report",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incomes",
                        to="core.financialreport",
                        verbose_name="گزارش مالی",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_incomes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="مسئول ثبت",
                    ),
                ),
            ],
            options={
                "verbose_name": "درآمد",
                "verbose_name_plural": "درآمدها",
                "ordering": ["-registration_date"],
            },
        ),
    ]
