# Generated by Django 4.2.7 on 2025-10-16 19:57

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_expense_options_alter_loan_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expense",
            name="recorded_by",
        ),
        migrations.RemoveField(
            model_name="income",
            name="recorded_by",
        ),
        migrations.AlterField(
            model_name="loanbuyerstatushistory",
            name="status_date",
            field=django_jalali.db.models.jDateField(
                blank=True,
                help_text="تاریخ وضعیت (اتومات به تاریخ امروز تنظیم می\u200cشود)",
                null=True,
                verbose_name="تاریخ ثبت وضعیت",
            ),
        ),
        migrations.DeleteModel(
            name="Revenue",
        ),
    ]
