# Generated by Django 4.2.7 on 2025-10-18 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0005_remove_expense_recorded_by_remove_income_recorded_by_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="loancreditor",
            options={
                "ordering": ["-creation_date"],
                "verbose_name": "بستانکار وام",
                "verbose_name_plural": "بستانکاران وام",
            },
        ),
        migrations.AddField(
            model_name="loan",
            name="applicant_first_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="نام صاحب وام"
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="applicant_last_name",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="نام خانوادگی صاحب وام",
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="applicant_phone",
            field=models.CharField(
                blank=True, max_length=11, null=True, verbose_name="شماره تماس صاحب وام"
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="recorded_by",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"profile__role": "employee"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="loans_recorded",
                to=settings.AUTH_USER_MODEL,
                verbose_name="مسئول ثبت وام",
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="referrer",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="معرفی\u200cکننده (نام فرد/شرکت)",
            ),
        ),
        migrations.AddField(
            model_name="loancreditor",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="loan_creditors",
                to="core.branch",
                verbose_name="شعبه مرتبط",
            ),
        ),
        migrations.AddField(
            model_name="loancreditor",
            name="broker",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"profile__role": "employee"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="loan_creditors_as_broker",
                to=settings.AUTH_USER_MODEL,
                verbose_name="کارگذار ثبت\u200cکننده",
            ),
        ),
        migrations.AddField(
            model_name="loancreditor",
            name="category",
            field=models.CharField(
                choices=[
                    ("individual", "شخصی"),
                    ("company", "شرکت"),
                    ("organization", "سازمان"),
                ],
                default="individual",
                max_length=20,
                verbose_name="دسته\u200cبندی بستانکار",
            ),
        ),
        migrations.AddField(
            model_name="loancreditor",
            name="creation_date",
            field=django_jalali.db.models.jDateField(
                auto_now_add=True, null=True, verbose_name="تاریخ ایجاد رکورد"
            ),
        ),
        migrations.AddField(
            model_name="loancreditor",
            name="final_notes",
            field=models.TextField(
                blank=True, null=True, verbose_name="یادداشت نهایی (هنگام تسویه)"
            ),
        ),
        migrations.AddField(
            model_name="loancreditor",
            name="first_name",
            field=models.CharField(default="", max_length=100, verbose_name="نام"),
        ),
        migrations.AddField(
            model_name="loancreditor",
            name="internal_document_number",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="شماره سند داخلی"
            ),
        ),
        migrations.AddField(
            model_name="loancreditor",
            name="internal_notes",
            field=models.TextField(
                blank=True, null=True, verbose_name="یادداشت\u200cهای داخلی"
            ),
        ),
        migrations.AddField(
            model_name="loancreditor",
            name="last_name",
            field=models.CharField(
                default="", max_length=100, verbose_name="نام خانوادگی"
            ),
        ),
        migrations.AddField(
            model_name="loancreditor",
            name="national_id",
            field=models.CharField(
                default="", max_length=10, unique=True, verbose_name="کد ملی"
            ),
        ),
        migrations.AddField(
            model_name="loancreditor",
            name="next_followup_date",
            field=django_jalali.db.models.jDateField(
                blank=True, null=True, verbose_name="تاریخ پیگیری بعدی"
            ),
        ),
        migrations.AddField(
            model_name="loancreditor",
            name="paid_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=15,
                verbose_name="جمع مبلغ پرداخت\u200cشده",
            ),
        ),
        migrations.AddField(
            model_name="loancreditor",
            name="payment_type",
            field=models.CharField(
                choices=[("cash", "نقدی"), ("installment", "قسطی")],
                default="installment",
                max_length=20,
                verbose_name="نوع پرداخت",
            ),
        ),
        migrations.AddField(
            model_name="loancreditor",
            name="settlement_date",
            field=django_jalali.db.models.jDateField(
                blank=True, null=True, verbose_name="تاریخ تسویه کامل"
            ),
        ),
        migrations.AddField(
            model_name="loancreditor",
            name="settlement_status",
            field=models.CharField(
                choices=[
                    ("unsettled", "انجام نشده"),
                    ("settled", "انجام شده"),
                    ("partial", "جزئی"),
                ],
                default="unsettled",
                max_length=20,
                verbose_name="وضعیت تسویه",
            ),
        ),
        migrations.AddField(
            model_name="loancreditor",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=15,
                verbose_name="مبلغ کل (نرخ خرید از وام)",
            ),
        ),
        migrations.AlterField(
            model_name="loancreditor",
            name="loan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="creditors",
                to="core.loan",
                verbose_name="وام مرتبط",
            ),
        ),
        migrations.AlterField(
            model_name="loancreditor",
            name="phone",
            field=models.CharField(
                default="", max_length=11, verbose_name="شماره تماس"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="loancreditor",
            unique_together={("national_id", "loan")},
        ),
        migrations.RemoveField(
            model_name="loancreditor",
            name="address",
        ),
        migrations.RemoveField(
            model_name="loancreditor",
            name="credit_amount",
        ),
        migrations.RemoveField(
            model_name="loancreditor",
            name="organization_name",
        ),
        migrations.RemoveField(
            model_name="loancreditor",
            name="remaining_debt",
        ),
        migrations.RemoveField(
            model_name="loancreditor",
            name="user",
        ),
        migrations.CreateModel(
            name="LoanCreditorInstallment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="مبلغ قسط"
                    ),
                ),
                (
                    "payment_date",
                    django_jalali.db.models.jDateField(
                        blank=True, null=True, verbose_name="تاریخ پرداخت قسط"
                    ),
                ),
                (
                    "installment_number",
                    models.PositiveIntegerField(verbose_name="شماره قسط"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("paid", "پرداخت شده"), ("unpaid", "پرداخت نشده")],
                        default="unpaid",
                        max_length=20,
                        verbose_name="وضعیت قسط",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="توضیحات قسط"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "creditor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="installments",
                        to="core.loancreditor",
                        verbose_name="بستانکار",
                    ),
                ),
            ],
            options={
                "verbose_name": "قسط بستانکار وام",
                "verbose_name_plural": "قسط\u200cهای بستانکار وام",
                "ordering": ["creditor", "installment_number"],
                "unique_together": {("creditor", "installment_number")},
            },
        ),
    ]
