# Generated by Django 4.2.7 on 2025-10-18 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0006_alter_loancreditor_options_loan_applicant_first_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loan",
            name="recorded_by",
        ),
        migrations.AlterField(
            model_name="activityreport",
            name="date",
            field=django_jalali.db.models.jDateField(verbose_name="تاریخ"),
        ),
        migrations.AlterField(
            model_name="activityreport",
            name="description",
            field=models.TextField(verbose_name="توضیحات"),
        ),
        migrations.AlterField(
            model_name="activityreport",
            name="hours_worked",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, verbose_name="ساعات کار"
            ),
        ),
        migrations.AlterField(
            model_name="activityreport",
            name="title",
            field=models.CharField(max_length=200, verbose_name="عنوان"),
        ),
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "ایجاد"),
                            ("update", "ویرایش"),
                            ("delete", "حذف"),
                            ("login", "ورود به سیستم"),
                            ("logout", "خروج از سیستم"),
                            ("download", "دانلود"),
                            ("export", "صادرات"),
                            ("import", "واردات"),
                            ("other", "سایر"),
                        ],
                        max_length=50,
                        verbose_name="عملیات",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="نوع مدل"
                    ),
                ),
                (
                    "object_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="شناسه رکورد",
                    ),
                ),
                (
                    "object_description",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="توضیح رکورد",
                    ),
                ),
                (
                    "details",
                    models.TextField(
                        blank=True,
                        help_text="تغییرات انجام\u200cشده به فرمت JSON",
                        null=True,
                        verbose_name="جزئیات تغییرات",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="آدرس IP"
                    ),
                ),
                (
                    "timestamp",
                    django_jalali.db.models.jDateTimeField(
                        auto_now_add=True, verbose_name="تاریخ و زمان"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "لاگ فعالیت",
                "verbose_name_plural": "لاگ\u200cهای فعالیت",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["-timestamp"], name="core_activi_timesta_8baae3_idx"
                    ),
                    models.Index(
                        fields=["user", "-timestamp"],
                        name="core_activi_user_id_d7adda_idx",
                    ),
                    models.Index(
                        fields=["action", "-timestamp"],
                        name="core_activi_action_1fc1d1_idx",
                    ),
                ],
            },
        ),
    ]
