# Generated by Django 4.2.7 on 2025-10-18 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0007_remove_loan_recorded_by_alter_activityreport_date_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Service",
        ),
        migrations.RemoveField(
            model_name="activityreport",
            name="hours_worked",
        ),
        migrations.RemoveField(
            model_name="branch",
            name="working_hours",
        ),
        migrations.AddField(
            model_name="activityreport",
            name="time",
            field=models.TimeField(blank=True, null=True, verbose_name="ساعت و دقیقه"),
        ),
        migrations.AddField(
            model_name="branch",
            name="working_end_time",
            field=models.TimeField(
                blank=True, null=True, verbose_name="ساعت پایان کاری"
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="working_start_time",
            field=models.TimeField(
                blank=True, null=True, verbose_name="ساعت شروع کاری"
            ),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="timestamp",
            field=django_jalali.db.models.jDateTimeField(
                auto_now_add=True, verbose_name="تاریخ و زمان ایجاد"
            ),
        ),
        migrations.AlterField(
            model_name="activityreport",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
        ),
        migrations.AlterField(
            model_name="activityreport",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_reports",
                to="core.employee",
                verbose_name="کارمند",
            ),
        ),
        migrations.AlterField(
            model_name="activityreport",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="date",
            field=models.DateField(verbose_name="تاریخ"),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendances",
                to="core.employee",
                verbose_name="کارمند",
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="notes",
            field=models.TextField(
                blank=True, null=True, verbose_name="یادداشت\u200cها"
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="status",
            field=models.CharField(
                choices=[
                    ("present", "حاضر"),
                    ("absent", "غایب"),
                    ("leave", "مرخصی"),
                    ("late", "تاخیر"),
                ],
                max_length=20,
                verbose_name="وضعیت",
            ),
        ),
        migrations.AlterField(
            model_name="casefile",
            name="assigned_lawyer",
            field=models.ForeignKey(
                limit_choices_to={"profile__role": "lawyer"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_cases",
                to=settings.AUTH_USER_MODEL,
                verbose_name="وکیل مسئول",
            ),
        ),
        migrations.AlterField(
            model_name="casefile",
            name="case_number",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="شماره پرونده"
            ),
        ),
        migrations.AlterField(
            model_name="casefile",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
        ),
        migrations.AlterField(
            model_name="casefile",
            name="description",
            field=models.TextField(verbose_name="توضیحات"),
        ),
        migrations.AlterField(
            model_name="casefile",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "در انتظار"),
                    ("in_progress", "در حال بررسی"),
                    ("completed", "تکمیل\u200cشده"),
                    ("closed", "بسته\u200cشده"),
                ],
                default="pending",
                max_length=20,
                verbose_name="وضعیت",
            ),
        ),
        migrations.AlterField(
            model_name="casefile",
            name="title",
            field=models.CharField(max_length=200, verbose_name="عنوان پرونده"),
        ),
        migrations.AlterField(
            model_name="casefile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
        ),
        migrations.AlterField(
            model_name="expense",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
        ),
        migrations.AlterField(
            model_name="expense",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
        ),
        migrations.AlterField(
            model_name="financialreport",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
        ),
        migrations.AlterField(
            model_name="financialreport",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="ایجاد\u200cشده توسط",
            ),
        ),
        migrations.AlterField(
            model_name="financialreport",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="توضیحات"),
        ),
        migrations.AlterField(
            model_name="financialreport",
            name="period_end",
            field=models.DateField(verbose_name="تاریخ پایان دوره"),
        ),
        migrations.AlterField(
            model_name="financialreport",
            name="period_start",
            field=models.DateField(verbose_name="تاریخ شروع دوره"),
        ),
        migrations.AlterField(
            model_name="financialreport",
            name="title",
            field=models.CharField(max_length=200, verbose_name="عنوان گزارش"),
        ),
        migrations.AlterField(
            model_name="financialreport",
            name="total_expense",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=15,
                verbose_name="کل هزینه\u200cها",
            ),
        ),
        migrations.AlterField(
            model_name="financialreport",
            name="total_revenue",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=15, verbose_name="کل درآمدها"
            ),
        ),
        migrations.AlterField(
            model_name="financialreport",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
        ),
        migrations.AlterField(
            model_name="income",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
        ),
        migrations.AlterField(
            model_name="income",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
        ),
        migrations.AlterField(
            model_name="loan",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
        ),
        migrations.AlterField(
            model_name="loan",
            name="loan_type",
            field=models.CharField(
                default="other",
                help_text="می\u200cتوانید یک نوع از لیست موجود انتخاب کنید یا مقدار دستی وارد کنید",
                max_length=50,
                verbose_name="نوع وام",
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="purchase_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=15,
                null=True,
                verbose_name="قیمت خرید وام",
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
        ),
        migrations.AlterField(
            model_name="loanbuyer",
            name="bank",
            field=models.CharField(
                blank=True, default="", max_length=150, verbose_name="بانک عامل"
            ),
        ),
        migrations.AlterField(
            model_name="loanbuyer",
            name="broker",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                limit_choices_to={"profile__role": "employee"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="loan_buyers_as_broker",
                to=settings.AUTH_USER_MODEL,
                verbose_name="کارگذار ثبت\u200cکننده",
            ),
        ),
        migrations.AlterField(
            model_name="loanbuyer",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
        ),
        migrations.AlterField(
            model_name="loanbuyer",
            name="current_status",
            field=models.CharField(
                choices=[
                    ("registered", "ثبت درخواست"),
                    ("under_review", "در حال بررسی"),
                    ("qualification_transfer", "انتقال امتیاز"),
                    ("bank_validation", "اعتبار سنجی بانک"),
                    ("loan_paid", "پرداخت وام"),
                    ("guarantor_defective", "نقص ضامن"),
                    ("borrower_defective", "نقص وام گیرنده"),
                    ("completed", "انجام شده"),
                ],
                default="registered",
                max_length=50,
                verbose_name="وضعیت فعلی",
            ),
        ),
        migrations.AlterField(
            model_name="loanbuyer",
            name="loan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="buyers",
                to="core.loan",
                verbose_name="وام هدف",
            ),
        ),
        migrations.AlterField(
            model_name="loanbuyer",
            name="sale_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=15,
                null=True,
                verbose_name="قیمت فروش",
            ),
        ),
        migrations.AlterField(
            model_name="loanbuyer",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
        ),
        migrations.AlterField(
            model_name="loanbuyerstatushistory",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
        ),
        migrations.AlterField(
            model_name="loanbuyerstatushistory",
            name="status",
            field=models.CharField(
                choices=[
                    ("registered", "ثبت درخواست"),
                    ("under_review", "در حال بررسی"),
                    ("qualification_transfer", "انتقال امتیاز"),
                    ("bank_validation", "اعتبار سنجی بانک"),
                    ("loan_paid", "پرداخت وام"),
                    ("guarantor_defective", "نقص ضامن"),
                    ("borrower_defective", "نقص وام گیرنده"),
                    ("completed", "انجام شده"),
                ],
                default="registered",
                max_length=50,
                verbose_name="وضعیت",
            ),
        ),
        migrations.AlterField(
            model_name="loancreditor",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
        ),
        migrations.AlterField(
            model_name="loancreditor",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
        ),
        migrations.AlterField(
            model_name="loancreditorinstallment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
        ),
        migrations.AlterField(
            model_name="loancreditorinstallment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="avatars/",
                verbose_name="تصویر پروفایل",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="bio",
            field=models.TextField(blank=True, null=True, verbose_name="درباره"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="department",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="دپارتمان"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="phone",
            field=models.CharField(
                blank=True, max_length=11, null=True, verbose_name="شماره تماس"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "ادمین"),
                    ("lawyer", "وکیل"),
                    ("employee", "کارمند"),
                ],
                default="employee",
                max_length=20,
                verbose_name="نقش",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="کاربر",
            ),
        ),
    ]
