# Generated by Django 4.2.7 on 2025-10-20 14:25

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_delete_service_remove_activityreport_hours_worked_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="address",
            field=models.TextField(
                blank=True, null=True, verbose_name="آدرس محل سکونت"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="bank_account_number",
            field=models.CharField(
                blank=True, max_length=24, null=True, verbose_name="شماره حساب بانکی"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="base_salary",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="حقوق پایه",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="benefits",
            field=models.TextField(
                blank=True, null=True, verbose_name="مزایا و اضافه کاری"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="birth_date",
            field=django_jalali.db.models.jDateField(
                blank=True, null=True, verbose_name="تاریخ تولد"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="profile_employees",
                to="core.branch",
                verbose_name="دپارتمان/شعبه",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="contract_end_date",
            field=django_jalali.db.models.jDateField(
                blank=True, null=True, verbose_name="تاریخ پایان قرارداد"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="contract_type",
            field=models.CharField(
                choices=[
                    ("full_time", "تمام وقت"),
                    ("part_time", "پاره وقت"),
                    ("project_based", "پروژه\u200cای"),
                    ("temporary", "موقت"),
                    ("intern", "کارآموزی"),
                ],
                default="full_time",
                max_length=50,
                verbose_name="نوع قرارداد",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="education",
            field=models.TextField(blank=True, null=True, verbose_name="تحصیلات"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="employment_status",
            field=models.CharField(
                choices=[
                    ("active", "فعال"),
                    ("leave", "مرخصی"),
                    ("inactive", "غیرفعال"),
                    ("terminated", "اخراج"),
                ],
                default="active",
                max_length=20,
                verbose_name="وضعیت فعلی",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "مرد"), ("F", "زن")],
                max_length=1,
                null=True,
                verbose_name="جنسیت",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="hire_date",
            field=django_jalali.db.models.jDateField(
                blank=True, null=True, verbose_name="تاریخ استخدام"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="insurance_info",
            field=models.TextField(
                blank=True, null=True, verbose_name="بیمه و مزایای رفاهی"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="internal_notes",
            field=models.TextField(
                blank=True, null=True, verbose_name="یادداشت\u200cهای داخلی"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="job_title",
            field=models.CharField(
                blank=True,
                choices=[
                    ("manager", "مدیر"),
                    ("officer", "افسر"),
                    ("assistant", "دستیار"),
                    ("intern", "کارآموز"),
                    ("lawyer", "وکیل"),
                    ("accountant", "حسابدار"),
                    ("hr", "منابع انسانی"),
                    ("it", "فناوری اطلاعات"),
                    ("other", "دیگر"),
                ],
                max_length=50,
                null=True,
                verbose_name="سمت/شغل",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="national_id",
            field=models.CharField(
                blank=True, max_length=10, null=True, unique=True, verbose_name="کد ملی"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="payment_method",
            field=models.CharField(
                choices=[("bank", "بانکی"), ("cash", "نقدی"), ("both", "هردو")],
                default="bank",
                max_length=20,
                verbose_name="روش پرداخت",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="personnel_id",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="شماره پرسنلی",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="employee_pictures/",
                verbose_name="عکس پرسنلی",
            ),
        ),
    ]
