# Generated by Django 4.2.7 on 2025-10-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_alter_userprofile_fields_final"),
    ]

    operations = [
        migrations.AddField(
            model_name="loancreditor",
            name="description",
            field=models.CharField(
                blank=True,
                default="",
                help_text="پر می\u200cشود به صورت خودکار هنگام ایجاد",
                max_length=255,
                verbose_name="شرح (ایدی وام - نوع وام - نام بانک)",
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="loan_type",
            field=models.CharField(
                default="",
                help_text="نوع وام را به صورت دستی وارد کنید (مثال: مسکن، شخصی، خودرو، کسب\u200cوکار، ...)",
                max_length=100,
                verbose_name="نوع وام",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="national_id",
            field=models.CharField(max_length=10, unique=True, verbose_name="کد ملی"),
        ),
    ]
