# Generated by Django 4.2.7 on 2025-10-20 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0013_loancreditor_description_alter_loan_loan_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="recorded_by",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"profile__role": "employee"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="loans_recorded",
                to=settings.AUTH_USER_MODEL,
                verbose_name="کارمند ثبت\u200cکننده",
            ),
        ),
        migrations.AddField(
            model_name="loancreditor",
            name="installment_count",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="تنها برای پرداخت قسطی - قسط\u200cها خودکار ایجاد می\u200cشوند",
                null=True,
                verbose_name="تعداد قسط\u200cهای برنامه\u200cریزی\u200cشده",
            ),
        ),
        migrations.AddField(
            model_name="loancreditor",
            name="recorded_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                limit_choices_to={"profile__role": "employee"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="loan_creditors_recorded",
                to=settings.AUTH_USER_MODEL,
                verbose_name="کارمند ثبت\u200cکننده (اتومات)",
            ),
        ),
        migrations.AddField(
            model_name="loancreditorinstallment",
            name="due_date",
            field=django_jalali.db.models.jDateField(
                blank=True, null=True, verbose_name="تاریخ سررسید قسط"
            ),
        ),
        migrations.AddField(
            model_name="loancreditorinstallment",
            name="paid_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=15,
                verbose_name="مبلغ پرداخت شده",
            ),
        ),
        migrations.AddField(
            model_name="loancreditorinstallment",
            name="related_loan",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="creditor_installments",
                to="core.loan",
                verbose_name="وام مرتبط",
            ),
        ),
    ]
