# Generated by Django 4.2.7 on 2025-10-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_loan_recorded_by_loancreditor_installment_count_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loancreditorinstallment",
            name="related_loan",
        ),
        migrations.AlterField(
            model_name="loancreditorinstallment",
            name="installment_number",
            field=models.PositiveIntegerField(editable=False, verbose_name="شماره قسط"),
        ),
    ]
