# Generated by Django 4.2.7 on 2025-10-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_remove_loancreditorinstallment_related_loan_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="applicant_national_id",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="کد ملی صاحب وام"
            ),
        ),
        migrations.AlterField(
            model_name="loancreditor",
            name="national_id",
            field=models.CharField(default="", max_length=10, verbose_name="کد ملی"),
        ),
    ]
