# Generated by Django 4.2.7 on 2025-10-21 15:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_loan_applicant_national_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expense",
            name="financial_report",
        ),
        migrations.RemoveField(
            model_name="income",
            name="financial_report",
        ),
        migrations.DeleteModel(
            name="FinancialReport",
        ),
    ]
