# Generated by Django 4.2.7 on 2025-10-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_remove_expense_financial_report_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loancreditorinstallment",
            name="amount",
        ),
        migrations.AlterField(
            model_name="loancreditorinstallment",
            name="paid_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=15,
                verbose_name="مبلغ قسط (پرداخت\u200cشده)",
            ),
        ),
    ]
