# Generated by Django 4.2.7 on 2025-10-21 18:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_loanbuyer_created_by"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CaseFile",
        ),
    ]
