# Generated by Django 4.2.7 on 2025-10-22 11:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0020_remove_casefile"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "standard_work_start",
                    models.TimeField(
                        default="08:00", verbose_name="ساعت شروع کاری استاندارد"
                    ),
                ),
                (
                    "standard_work_end",
                    models.TimeField(
                        default="17:00", verbose_name="ساعت پایان کاری استاندارد"
                    ),
                ),
                (
                    "standard_work_hours",
                    models.IntegerField(
                        default=480, verbose_name="ساعات کاری روزانه (دقیقه)"
                    ),
                ),
                (
                    "max_daily_overtime",
                    models.IntegerField(
                        default=120,
                        verbose_name="حداکثر اضافه\u200cکاری روزانه (دقیقه)",
                    ),
                ),
                (
                    "max_monthly_overtime",
                    models.IntegerField(
                        default=2400,
                        verbose_name="حداکثر اضافه\u200cکاری ماهانه (دقیقه)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="آخرین به\u200cروزرسانی"
                    ),
                ),
            ],
            options={
                "verbose_name": "تنظیمات شرکت",
                "verbose_name_plural": "تنظیمات شرکت",
            },
        ),
        migrations.AlterModelOptions(
            name="attendance",
            options={
                "ordering": ["-date", "-check_in"],
                "verbose_name": "حضور و غیاب",
                "verbose_name_plural": "حضور و غیاب\u200cها",
            },
        ),
        migrations.AddField(
            model_name="attendance",
            name="check_in",
            field=models.TimeField(blank=True, null=True, verbose_name="ساعت ورود"),
        ),
        migrations.AddField(
            model_name="attendance",
            name="check_out",
            field=models.TimeField(blank=True, null=True, verbose_name="ساعت خروج"),
        ),
        migrations.AddField(
            model_name="attendance",
            name="overtime_duration",
            field=models.IntegerField(
                blank=True,
                default=0,
                null=True,
                verbose_name="مدت اضافه\u200cکاری (دقیقه)",
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="آخرین به\u200cروزرسانی"
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="work_duration",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="مدت زمان کار (دقیقه)"
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="status",
            field=models.CharField(
                choices=[
                    ("present", "حاضر"),
                    ("absent", "غایب"),
                    ("leave", "مرخصی"),
                    ("late", "تاخیر"),
                    ("incomplete", "ناقص"),
                    ("early_leave", "خروج زودهنگام"),
                ],
                default="present",
                max_length=20,
                verbose_name="وضعیت",
            ),
        ),
    ]
