# Generated by Django 4.2.7 on 2025-10-22 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0021_companysettings_alter_attendance_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Leave",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("annual", "مرخصی سالانه"),
                            ("sick", "مرخصی بیماری"),
                            ("personal", "مرخصی شخصی"),
                            ("maternity", "مرخصی زایمان"),
                            ("paternity", "مرخصی پدری"),
                            ("unpaid", "مرخصی بدون\u200cحقوق"),
                            ("half_day", "نیم\u200cروز"),
                        ],
                        max_length=20,
                        verbose_name="نوع مرخصی",
                    ),
                ),
                (
                    "start_date",
                    django_jalali.db.models.jDateField(verbose_name="تاریخ شروع"),
                ),
                (
                    "end_date",
                    django_jalali.db.models.jDateField(verbose_name="تاریخ پایان"),
                ),
                (
                    "duration",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="مدت (روز)"
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True, null=True, verbose_name="دلیل/توضیحات"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار تایید"),
                            ("approved", "تایید شده"),
                            ("rejected", "رد شده"),
                            ("cancelled", "لغو شده"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "approval_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاریخ تایید"
                    ),
                ),
                (
                    "approval_notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="یادداشت\u200cهای تایید"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاریخ درخواست"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="آخرین به\u200cروزرسانی"
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_leaves",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تایید\u200cشده توسط",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leaves",
                        to="core.employee",
                        verbose_name="کارمند",
                    ),
                ),
            ],
            options={
                "verbose_name": "مرخصی",
                "verbose_name_plural": "مرخصی\u200cها",
                "ordering": ["-created_at"],
            },
        ),
    ]
