# Generated by Django 4.2.7 on 2025-10-22 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0023_add_hourly_leave_support"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان")),
                ("message", models.TextField(verbose_name="پیام")),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("leave_request", "درخواست مرخصی"),
                            ("leave_approved", "مرخصی تایید شده"),
                            ("leave_rejected", "مرخصی رد شده"),
                            ("attendance_alert", "هشدار حضور"),
                            ("overtime_alert", "هشدار اضافه\u200cکاری"),
                            ("system_alert", "هشدار سیستم"),
                        ],
                        max_length=30,
                        verbose_name="نوع نوتیف",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="نوع محتوا"
                    ),
                ),
                (
                    "object_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="شناسه رکورد"
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="خوانده شده"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاریخ خواندن"
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="گیرنده",
                    ),
                ),
            ],
            options={
                "verbose_name": "نوتیف",
                "verbose_name_plural": "نوتیف\u200cها",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "-created_at"],
                        name="core_notifi_recipie_4d7e73_idx",
                    ),
                    models.Index(
                        fields=["recipient", "is_read"],
                        name="core_notifi_recipie_aeffaf_idx",
                    ),
                ],
            },
        ),
    ]
