# Generated by Django 4.2.7 on 2025-10-22 19:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0025_attendance_and_weekly_schedule"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="recipient",
        ),
        migrations.RemoveConstraint(
            model_name="dayworkschedule",
            name="unique_day_schedule",
        ),
        migrations.AlterUniqueTogether(
            name="dayworkschedule",
            unique_together={("company_settings", "day_of_week")},
        ),
        migrations.DeleteModel(
            name="Notification",
        ),
    ]
