# Generated by Django 4.2.7 on 2025-10-22 19:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0026_populate_day_schedules"),
        ("core", "0026_remove_notification_recipient_and_more"),
    ]

    operations = []
