# Generated by Django 4.2.7 on 2025-10-22 19:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0027_merge_20251022_2251"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="dayworkschedule",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="dayworkschedule",
            name="company_settings",
        ),
        migrations.DeleteModel(
            name="CompanySettings",
        ),
        migrations.DeleteModel(
            name="DayWorkSchedule",
        ),
    ]
