# Generated by Django 4.2.7 on 2025-10-24 13:09

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0028_delete_company_settings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="hire_date",
            field=django_jalali.db.models.jDateField(
                blank=True, null=True, verbose_name="تاریخ استخدام"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="hire_date",
            field=django_jalali.db.models.jDateField(
                blank=True, null=True, verbose_name="تاریخ استخدام"
            ),
        ),
    ]
